// export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE TASK";
export const EDIT_TASK = "EDIT_TASK";
export const MARK_COMPLETED = "MARK_COMPLETED";
export const DISPLAY_TASKS = "DISPLAY_TASKS";
export const SEARCH_TASKS = "SEARCH_TASKS";
export const GET_TODOS = "GET_TODOS";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SUBMIT = "SUBMIT";
